version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: san3
      MYSQL_DATABASE: mydb

  adminer:
    image: adminer
    restart: always
    networks: 
      - backend
    ports:
      - 8081:8080
    depends_on: 
      - mysql

networks:
  frontend:
  backend: